### ISSUE TITLE
기능 구현 - 메인 인덱스(/index) - 흥한갤

### ISSUE THREAD

**Issue by realKimJaeJun** [hochmun/3th_team_project#320]

**Comment by realKimJaeJun** [comment]
- [ ] 기준 -> { 1 : 24시간 동안 글 리젠 (게시글, 댓글, 대댓글) 많은 순, 2 : }
- [ ] 랭킹 메기기 -> 24시간 전 순위도 같이 구해서 비교 하기
- [ ] 갤러리 10개씩 50개 출력 
- [ ] 메인 , 마이너, 미니  출력
- [ ] 동적 처리

**Comment by hochmun** [comment]
2023/04/26 // 심규영 // 흥한 갤 작업 완료
