### ISSUE TITLE
화면구현 - 이용약관(policy/index)

### ISSUE THREAD

**Issue by asdeqqga** [hochmun/3th_team_project#47]
2023/03/07 // 라성준 // 작업
2023/03/08 // 라성준 // 유료서비스 이용약관, 개인정보처리방침 쉬운버전 작업

**Comment by asdeqqga** [comment]
- [ ] 지시인사이드 이용약관(policy/index)
- [ ] 유료서비스 이용약관(pay/policy)
-----------------------------------------------------
- [ ] 개인정보처리방침(privacy_index)
- [ ] 개인정보처리방침 쉬운버전(privacy_young)
------------------------------------------------------

- [ ] 청소년보호정책

**Comment by hochmun** [comment]
리뷰 완료
